-- MySQL Script generated by MySQL Workbench
-- mié 09 mar 2016 12:49:04 MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

use markoptic;
-- -----------------------------------------------------
-- Table `mydb`.`Padrinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padrinos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `fec_nac` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

-- -----------------------------------------------------
-- Table `mydb`.`Apadrinamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Apadrinamientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_padrino` INT NOT NULL,
  `id_ben` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Apadrinamientos_1_idx` (`id_padrino` ASC),
  INDEX `fk_Apadrinamientos_2_idx` (`id_ben` ASC),
  CONSTRAINT `fk_Apadrinamientos_1`
    FOREIGN KEY (`id_padrino`)
    REFERENCES `Padrinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apadrinamientos_2`
    FOREIGN KEY (`id_ben`)
    REFERENCES `beneficiario_solicitud` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Donativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Donativos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `metodo` VARCHAR(45) NULL DEFAULT NULL,
  `monto` DOUBLE NULL DEFAULT NULL,
  `referencia` VARCHAR(45) NULL DEFAULT NULL,
  `doc_comprobacion` VARCHAR(255) NULL DEFAULT NULL,
  `comprobante` TINYINT(1) NOT NULL DEFAULT 0,
  `id_apadrinamiento` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Donativos_1_idx` (`id_apadrinamiento` ASC),
  CONSTRAINT `fk_Donativos_1`
    FOREIGN KEY (`id_apadrinamiento`)
    REFERENCES `Apadrinamientos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
